/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import horario.Horario;
import horario.Materia;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JETZ
 */
public class Aplicacion extends javax.swing.JFrame {

    private DefaultListModel modeloLista = new DefaultListModel();
    private ArrayList list = new ArrayList();
    private boolean[] vectorFlag = new boolean[100];
    private int cantidad=0;
    private Horario horario;
    
    public void generarVector(){
        for(int i=0;i<vectorFlag.length;i++){
            vectorFlag[i]=false;
        }
    }
    public void limpiarHorario(){
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", null, null, null, null, null, null},
                {"7", null, null, null, null, null, null},
                {"8", null, null, null, null, null, null},
                {"9", null, null, null, null, null, null},
                {"10", null, null, null, null, null, null},
                {"11", null, null, null, null, null, null},
                {"12", null, null, null, null, null, null},
                {"13", null, null, null, null, null, null},
                {"14", null, null, null, null, null, null},
                {"15", null, null, null, null, null, null},
                {"16", null, null, null, null, null, null},
                {"17", null, null, null, null, null, null},
                {"18", null, null, null, null, null, null},
                {"19", null, null, null, null, null, null},
                {"20", null, null, null, null, null, null},
                {"21", null, null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    public Aplicacion() {
        initComponents();
        
      generarVector();
      //jTable1.setValueAt("Prueba", 0, 1);
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jBtAgregar = new javax.swing.JButton();
        jBtGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", null, null, null, null, null, null},
                {"7", null, null, null, null, null, null},
                {"8", null, null, null, null, null, null},
                {"9", null, null, null, null, null, null},
                {"10", null, null, null, null, null, null},
                {"11", null, null, null, null, null, null},
                {"12", null, null, null, null, null, null},
                {"13", null, null, null, null, null, null},
                {"14", null, null, null, null, null, null},
                {"15", null, null, null, null, null, null},
                {"16", null, null, null, null, null, null},
                {"17", null, null, null, null, null, null},
                {"18", null, null, null, null, null, null},
                {"19", null, null, null, null, null, null},
                {"20", null, null, null, null, null, null},
                {"21", null, null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBtSalir.setText("Salir");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jBtAgregar.setText("Agregar");
        jBtAgregar.setToolTipText("Agrega un bloque a la misma materia");
        jBtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgregarActionPerformed(evt);
            }
        });

        jBtGuardar.setText("Limpiar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem1.setText("Acerca de...");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAgregar)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtSalirActionPerformed
    public boolean existe(Materia m){
        boolean verdad=false;
        Materia m1;
        for(int x=0;x <list.size();x++){
            m1=(Materia)list.get(x);
            if(m.getNombre().equals(m1.getNombre())){
                if(m.getDia()==m1.getDia()){
                    if(m.gethInicio()==m1.gethInicio()){
                        if(m.gethFinal()==m1.gethFinal()){
                            if(m.getSalon().equals(m1.getSalon()))
                                verdad=true;
                        }
                    }
                }
            }
        }
        return verdad;
    }
    private void jBtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAgregarActionPerformed
        Materia mat = new Materia(jTextField1.getText(),jcbHoraInicio.getSelectedIndex()+6,jcbHoraFin.getSelectedIndex()+6,jcbDia.getSelectedIndex()+1,jcbGrupo.getText());
        
        if(existe(mat)&&!(list.isEmpty())){
            JOptionPane.showMessageDialog(null, "Materia y horario existente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            if(jcbHoraInicio.getSelectedIndex()>=jcbHoraFin.getSelectedIndex()){
                JOptionPane.showMessageDialog(null, "Horario inválido", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else if((jTextField1.getText().isEmpty())||(jcbGrupo.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Textos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else{

                list.add(mat);
                modeloLista.addElement("("+mat.getSalon()+") "+mat.getNombre());
                jList1.setModel(modeloLista);

                //jTextField1.setText("");
                //jTextField2.setText("");
            }
        }
        limpiarHorario();
        generarVector();
    }//GEN-LAST:event_jBtAgregarActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        boolean arreglameLaVida=false;
        int i=jList1.getSelectedIndex();
        int hI,hF,c=0,tamano;
        
        Materia aux = (Materia)(list.get(i));
        tamano = jList1.getModel().getSize();
        //JOptionPane.showMessageDialog(null, "Valor: "+vectorFlag[i], "Advertencia", JOptionPane.WARNING_MESSAGE);

        if(vectorFlag[i]==false){
            for(int x=0;x<tamano;x++){
                Materia nombreTemp= (Materia)list.get(x);
                if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                    c=0;
                    hI=nombreTemp.gethInicio()-6;
                    hF=nombreTemp.gethFinal()-6;

                    while((hI+c)<hF){
                        //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);

                        if(jTable1.getValueAt(hI+c, nombreTemp.getDia())==null){
                            c++;
                        }
                        else{
                            arreglameLaVida=true;
                            JOptionPane.showMessageDialog(null, "Cruce de horario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    }

                }
            }

            if(!arreglameLaVida){
                for(int x=0;x<tamano;x++){
                    Materia nombreTemp= (Materia)list.get(x);
                    if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                        c=0;
                        hI=nombreTemp.gethInicio()-6;
                        hF=nombreTemp.gethFinal()-6;

                        while((hI+c)<hF){
                            //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);

                            jTable1.setValueAt("("+nombreTemp.getSalon()+")"+nombreTemp.getNombre(), hI+c, nombreTemp.getDia());
                            c++;

                        }
                        vectorFlag[x]=true;
                    }
                }
            }
        }
        else{
            for(int x=0;x<tamano;x++){
                Materia nombreTemp= (Materia)list.get(x);
                if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                    c=0;
                    hI=nombreTemp.gethInicio()-6;
                    hF=nombreTemp.gethFinal()-6;

                    while((hI+c)<hF){
                        //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);
                        jTable1.setValueAt(null, hI+c, nombreTemp.getDia());
                        c++;                        
                    }
                    vectorFlag[x]=false;
                }
            }
        }
        
        

        
    }//GEN-LAST:event_jList1MouseClicked

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
           /* 
            list.add(mat);
            modeloLista.addElement("("+mat.getSalon()+") "+mat.getNombre());
            jList1.setModel(modeloLista);

            jTextField1.setText("");
            jTextField2.setText("");
        */
        limpiarHorario();
        generarVector();
    }//GEN-LAST:event_jBtGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAgregar;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JButton jBtSalir;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
