/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import horario.Materia;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JETZ
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    DefaultListModel modeloLista = new DefaultListModel();
    ArrayList list = new ArrayList();
    boolean[] vectorFlag = new boolean[100];
    int cantidad=0;
    
    public void generarVector(){
        for(int i=0;i<vectorFlag.length;i++){
            vectorFlag[i]=false;
        }
    }
    public void limpiarHorario(){
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", null, null, null, null, null, null},
                {"7", null, null, null, null, null, null},
                {"8", null, null, null, null, null, null},
                {"9", null, null, null, null, null, null},
                {"10", null, null, null, null, null, null},
                {"11", null, null, null, null, null, null},
                {"12", null, null, null, null, null, null},
                {"13", null, null, null, null, null, null},
                {"14", null, null, null, null, null, null},
                {"15", null, null, null, null, null, null},
                {"16", null, null, null, null, null, null},
                {"17", null, null, null, null, null, null},
                {"18", null, null, null, null, null, null},
                {"19", null, null, null, null, null, null},
                {"20", null, null, null, null, null, null},
                {"21", null, null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    public Aplicacion() {
        initComponents();
        
      generarVector();
      //jTable1.setValueAt("Prueba", 0, 1);
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jBtAgregar = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jlHoraInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlDia = new javax.swing.JLabel();
        jcbDia = new javax.swing.JComboBox();
        jcbHoraInicio = new javax.swing.JComboBox();
        jcbHoraFin = new javax.swing.JComboBox();
        jlGrupo = new javax.swing.JLabel();
        jcbGrupo = new javax.swing.JTextField();
        jBtGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", null, null, null, null, null, null},
                {"7", null, null, null, null, null, null},
                {"8", null, null, null, null, null, null},
                {"9", null, null, null, null, null, null},
                {"10", null, null, null, null, null, null},
                {"11", null, null, null, null, null, null},
                {"12", null, null, null, null, null, null},
                {"13", null, null, null, null, null, null},
                {"14", null, null, null, null, null, null},
                {"15", null, null, null, null, null, null},
                {"16", null, null, null, null, null, null},
                {"17", null, null, null, null, null, null},
                {"18", null, null, null, null, null, null},
                {"19", null, null, null, null, null, null},
                {"20", null, null, null, null, null, null},
                {"21", null, null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBtSalir.setText("Salir");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jBtAgregar.setText("Agregar");
        jBtAgregar.setToolTipText("Agrega un bloque a la misma materia");
        jBtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgregarActionPerformed(evt);
            }
        });

        jlNombre.setText("Nombre");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jlHoraInicio.setText("Hora entrada");

        jLabel3.setText("Hora salida");

        jlDia.setText("Día");

        jcbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

        jcbHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));

        jcbHoraFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));
        jcbHoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHoraFinActionPerformed(evt);
            }
        });

        jlGrupo.setText("Grupo");

        jBtGuardar.setText("Limpiar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Powered by:JETZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtAgregar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlHoraInicio)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlDia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jcbHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlGrupo)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcbDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbGrupo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtGuardar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jcbHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombre)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDia)
                    .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHoraInicio)
                    .addComponent(jcbHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGrupo)
                    .addComponent(jcbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcbHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSalir)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtAgregar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtSalirActionPerformed
    public boolean existe(Materia m){
        boolean verdad=false;
        Materia m1;
        for(int x=0;x <list.size();x++){
            m1=(Materia)list.get(x);
            if(m.getNombre().equals(m1.getNombre())){
                if(m.getDia()==m1.getDia()){
                    if(m.gethInicio()==m1.gethInicio()){
                        if(m.gethFinal()==m1.gethFinal()){
                            if(m.getSalon().equals(m1.getSalon()))
                                verdad=true;
                        }
                    }
                }
            }
        }
        return verdad;
    }
    private void jBtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAgregarActionPerformed
        Materia mat = new Materia(jTextField1.getText(),jcbHoraInicio.getSelectedIndex()+6,jcbHoraFin.getSelectedIndex()+6,jcbDia.getSelectedIndex()+1,jcbGrupo.getText());
        
        if(existe(mat)&&!(list.isEmpty())){
            JOptionPane.showMessageDialog(null, "Materia y horario existente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            if(jcbHoraInicio.getSelectedIndex()>=jcbHoraFin.getSelectedIndex()){
                JOptionPane.showMessageDialog(null, "Horario inválido", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else if((jTextField1.getText().isEmpty())||(jcbGrupo.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Textos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else{

                list.add(mat);
                modeloLista.addElement("("+mat.getSalon()+") "+mat.getNombre());
                jList1.setModel(modeloLista);

                //jTextField1.setText("");
                //jTextField2.setText("");
            }
        }
        limpiarHorario();
        generarVector();
    }//GEN-LAST:event_jBtAgregarActionPerformed

    private void jcbHoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHoraFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHoraFinActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        boolean arreglameLaVida=false;
        int i=jList1.getSelectedIndex();
        int hI,hF,c=0,tamano;
        
        Materia aux = (Materia)(list.get(i));
        tamano = jList1.getModel().getSize();
        //JOptionPane.showMessageDialog(null, "Valor: "+vectorFlag[i], "Advertencia", JOptionPane.WARNING_MESSAGE);

        if(vectorFlag[i]==false){
            for(int x=0;x<tamano;x++){
                Materia nombreTemp= (Materia)list.get(x);
                if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                    c=0;
                    hI=nombreTemp.gethInicio()-6;
                    hF=nombreTemp.gethFinal()-6;

                    while((hI+c)<hF){
                        //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);

                        if(jTable1.getValueAt(hI+c, nombreTemp.getDia())==null){
                            c++;
                        }
                        else{
                            arreglameLaVida=true;
                            JOptionPane.showMessageDialog(null, "Cruce de horario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    }

                }
            }

            if(!arreglameLaVida){
                for(int x=0;x<tamano;x++){
                    Materia nombreTemp= (Materia)list.get(x);
                    if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                        c=0;
                        hI=nombreTemp.gethInicio()-6;
                        hF=nombreTemp.gethFinal()-6;

                        while((hI+c)<hF){
                            //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);

                            jTable1.setValueAt("("+nombreTemp.getSalon()+")"+nombreTemp.getNombre(), hI+c, nombreTemp.getDia());
                            c++;

                        }
                        vectorFlag[x]=true;
                    }
                }
            }
        }
        else{
            for(int x=0;x<tamano;x++){
                Materia nombreTemp= (Materia)list.get(x);
                if((nombreTemp.getNombre().equals(aux.getNombre()))&&(nombreTemp.getSalon().equals(aux.getSalon()))){//Busca los iguales
                    c=0;
                    hI=nombreTemp.gethInicio()-6;
                    hF=nombreTemp.gethFinal()-6;

                    while((hI+c)<hF){
                        //JOptionPane.showMessageDialog(null, jTable1.getValueAt(hI+c, aux.getDia()), "Advertencia", JOptionPane.WARNING_MESSAGE);
                        jTable1.setValueAt(null, hI+c, nombreTemp.getDia());
                        c++;                        
                    }
                    vectorFlag[x]=false;
                }
            }
        }
        
        

        
    }//GEN-LAST:event_jList1MouseClicked

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
           /* 
            list.add(mat);
            modeloLista.addElement("("+mat.getSalon()+") "+mat.getNombre());
            jList1.setModel(modeloLista);

            jTextField1.setText("");
            jTextField2.setText("");
        */
        limpiarHorario();
        generarVector();
    }//GEN-LAST:event_jBtGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAgregar;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JButton jBtSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox jcbDia;
    private javax.swing.JTextField jcbGrupo;
    private javax.swing.JComboBox jcbHoraFin;
    private javax.swing.JComboBox jcbHoraInicio;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlGrupo;
    private javax.swing.JLabel jlHoraInicio;
    private javax.swing.JLabel jlNombre;
    // End of variables declaration//GEN-END:variables
}
